apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.fastpassName}}
  name: {{ .Values.fastpassName}}
spec:
  ports:
  - name: "8083"
    port: {{ .Values.fastpassPort}}
    targetPort: {{ .Values.fastpassPort}}
  type: {{ .Values.fastpassServicetype}}
  selector:
    io.kompose.service: {{ .Values.fastpassName}}
status:
  loadBalancer: {}
