apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.tollRateServiceName}}
  name: {{ .Values.tollRateServiceName}}
spec:
  ports:
  - name: "8084"
    port: {{ .Values.tollRateServicePort}}
    targetPort: {{ .Values.tollRateServicePort}}
  type: {{ .Values.tollRateServiceServicetype}}
  selector:
    io.kompose.service: {{ .Values.tollRateServiceName}}
status:
  loadBalancer: {}
